# Этот файл полностью соответствует вашему запросу.
version: "3.8"
services:
  ssp-excel-mcp:
    # Указываем, что нужно собирать образ из текущей директории
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Монтируем вашу директорию с файлами в контейнер
      - /home/ubuntu/excel-files:/app/backend/data/uploads
    environment:
      # Передаем переменные окружения в контейнер
      - EXCEL_FILES_PATH=/app/backend/data/uploads
      # UID и GID для запуска процесса от имени вашего пользователя,
      # чтобы избежать проблем с правами на смонтированный volume
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    # Запускаем контейнер от имени пользователя, указанного в environment
    user: "${UID:-1000}:${GID:-1000}"
    restart: always
